Added RHEL to linux distros, reworked file

diff --git a/scripts/linux b/scripts/linux
--- a/scripts/linux
+++ b/scripts/linux
@@ -1,13 +1,28 @@
 #!/bin/bash
-# TODO: This script currently only works in Arch Linux, need to generalise it
+# TODO: Add more distros. Currently only executes on Arch or Centos/RHEL
 
 # Include functions
 source scripts/functions
 
-# Install required packages
-PACMAN_PKG="fzf gcc python-pip rsync sudo vim zsh"
-if [[ $UID == 0 ]]; then
-    run pacman -S --noconfirm --needed $PACMAN_PKG
+if [[ -e /etc/redhat-release ]]; then
+    DISTRO="redhat"
+    PACKAGES="fzf gcc python-pip rsync sudo vim zsh"
+    RUN_COMMAND="yum install -y "
+elif [[ -e /etc/arch-release ]]; then
+    DISTRO="arch"
+    PACKAGES="fzf gcc python-pip rsync sudo vim zsh"
+    RUN_COMMAND="pacman -S --noconfirm --needed "
 else
-    run sudo pacman -S --noconfirm --needed $PACMAN_PKG
+    echo "ERROR: Could not determine Linux distribution, exiting..."
+    exit 1
 fi
+
+# Check if elevation is required
+if [[ $UID != 0 ]]; then
+    ELEVATE="sudo "
+else
+    ELEVATE=""
+fi
+
+# Install required packages
+run $ELEVATE $RUN_COMMAND $PACKAGES
